version: "3"

services:
  verifier:
    image: ethereumoptimism/go-ethereum:latest
    volumes:
      - verifier:/root/.ethereum:rw
    env_file:
      - docker-compose.env
    environment:
      - ROLLUP_VERIFIER_ENABLE=true
      - CHAIN_ID=10
      - NETWORK_ID=10
      - DEV=true
      - DATADIR=/root/.ethereum
      - RPC_ENABLE=true
      - RPC_ADDR=verifier
      - RPC_CORS_DOMAIN=*
      - RPC_VHOSTS=*
      - RPC_PORT=8045
      - WS=true
      - WS_ADDR=0.0.0.0
      - WS_PORT=8046
      - IPC_DISABLE=true
      - RPC_API=eth,net,rollup,web3
      - WS_API=eth,net,rollup,web3
      - WS_ORIGINS=*
      - GASPRICE=0
      - NO_USB=true
      - GCMODE=archive
      - NO_DISCOVER=true
      - USING_OVM=true
      - ETH1_SYNC_SERVICE_ENABLE=true
      - ETH1_CONFIRMATION_DEPTH=10
      - ETH1_CHAINID=1
      - ETH1_NETWORKID=1
      - ETH1_CTC_DEPLOYMENT_HEIGHT=11654116
      - ETH1_ADDRESS_RESOLVER_ADDRESS=0x1De8CFD4C1A486200286073aE91DE6e8099519f1
      - TARGET_GAS_LIMIT=9000000
      - ETH1_L1_CROSS_DOMAIN_MESSENGER_ADDRESS=0xfBE93ba0a2Df92A8e8D40cE00acCF9248a6Fc812
      - ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS=0xc6Dbc2DC7649c7d4292d955DA08A7C21a21e1528
      - ROLLUP_STATE_DUMP_PATH=https://raw.githubusercontent.com/ethereum-optimism/regenesis/master/mainnet/1.json
      - ROLLUP_DIFFDB_CACHE=1
    ports:
      - 8045:8045
      - 8046:8046

  fraud_prover:
    image: ethereumoptimism/fraud-prover:latest
    env_file:
      - docker-compose.env
    environment:
      - NO_TIMEOUT=true
      - L2_NODE_WEB3_URL=http://verifier:8045
      - L1_START_OFFSET=22610276
      - POLLING_INTERVAL=5000
      - RUN_GAS_LIMIT=8999999
      - RELAY_GAS_LIMIT=8999999
      - FROM_L2_TRANSACTION_INDEX=1
      - L2_BLOCK_OFFSET=1

volumes:
  verifier:
